### ISSUE TITLE
Proposal: Collect all builtin commands under a `meta` group

### ISSUE THREAD

**Issue by jdevera** [criteo/command-launcher#138]
When running a fresh install of the launcher, there is too much builtin already there. I added a single group and it was lost in the long list of options.

I also wanted to run my own config command, which manages the config for what the launcher semantically represents, but had to call it cfg and now cfg and config kind of clash, whereas "cl meta config" makes it clearer that is the config for the command itself.

I would perhaps make an exception for the help command.

What do you think?

**Comment by bhou** [comment]
I think grouping these commands into a meta group might cause two problems: 
1. Backward compatibility: When a new version is released, the existing systems that rely on this command will need to be updated to adapt to this change
2. It is less straight forward, as the help, version, config, update logically are actions on the command launcher itself.

Another aspect of this topic is that the principle of command launcher highly relying on the auto-complete feature, for most use case, the commands are accessed from auto-completion, where only few options are prompted. However, your concern is still valid when there are lots of the command in the `cl help` output. Today's output mixed both the built-in commands and plugin commands together, which make it difficult to identify the right one.

I would propose to improve the help message by grouping the commands by its package and registry, similar to the `kubectl` tool, here is a mockup:

```
Criteo Dev Toolkit - A command launcher 🚀 made with <3

Happy Coding!

Example:
  cdt --help

Usage:
  cdt [flags]
  cdt [command]

Commands from package (name-of-the-package) in registry (registry name):
  create          Create a resource from a file or from stdin
  expose          Take a replication controller, service, deployment or pod and expose it as a new Kubernetes service
  run                Run a particular image on the cluster
  set                Set specific features on objects

Built-in Commands:
  config            Config the command launcher
  version          Print the version
  update          Check update of the command launcher
  rename         Rename command
  help               Print help message
```

**Comment by jdevera** [comment]
I understand the backwards compatibility concerns, and I'd be happy with this compromise. It is clearer than today and still compatible.

**Comment by jdevera** [comment]
works beautifully, thank you!
