### ISSUE TITLE
What is the Github status of this project?

### ISSUE THREAD

**Issue by jdevera** [criteo/command-launcher#139]
Hi there,

I'm super happy this project exists and you have released it as open source, I use it to drive all of my homelab automation and it's just great! The automatic updates mean that it's always up to date in any machine I log into.

I have some ideas, suggestions, hiccups, etc. that I find during my use and I'd like to share them, sometimes I even may go for a PR. But I did send a PR and it has gone unactioned/unanswered for two months, while there have been code changes in the same period. Same for a question in the Discussions tab.

I am in no rush, so if it just takes months, I can adapt my expectations happily. But it is fair to ask if you are receptive to contributions in the form of suggestions or PRs from people outside of your company.

**Comment by bhou** [comment]
Hi,

Thanks for your interest in this project. It is great to hear that it helps in your use case. We are open to any contributions to this project (that's the purpose of open source). Summer is usually vacation time, and the team's capacity is low, so the PRs and issues might not be responded to as fast as usual. 

I will take a look at the issues and PRs you created by the end of this week; let's start from there.

Thanks again for your interest and contribution!

**Comment by jdevera** [comment]
That is wonderful, and thank you so much for the quick reply 🙏
